sudo: false
anguage: node_js
node_js: stable
#  - 10 # use nodejs v10 LTS
cache: 
  yarn: true
  directories:
  - node_modules
  - themes

branches:
  only:
    - master # build master branch only

before_install:
#  - npm install hexo-cli -g
  - npm install hexo
install:
  - npm install

script:
 # - hexo clean
  - hexo generate # generate static files

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: hexoblog/public